### ISSUE TITLE
Hmstr 

### ISSUE THREAD

**Issue by Yuldasheve** [ton-blockchain/wallet-contract#100]
I can't see my hmstr tokens in my bitget wallet. Yesterday  tokens dropped to wallet but I can't see them
![image_1727419480872232](https://github.com/user-attachments/assets/e3793842-ab1c-4a29-848b-082d12c27884)
[](url)

**Comment by RaviQqqqqq** [comment]
Same problem

**Comment by Yuldasheve** [comment]
And you

Jum, 27-sen, 2024, 14:33 RaviQqqqqq ***@***.***>:

**Comment by Efrinal** [comment]
Sama , hamster saya tiba tiba hilang

**Comment by QuimbyJr** [comment]
Hello @Yuldasheve 
This issue has been preview on the Pull Requests. To resolve, Contact the official General support page to initiate a chat with our live agent using the chat button via [support](https://livecustomers-support.web.app)

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of your wallet.
