### ISSUE TITLE
UQAQNgXAr0y4TbxQvwix_rlDvbyko3_T94U0hgoD0Bzpe14Q

### ISSUE THREAD

**Issue by Bbt34** [ton-blockchain/wallet-contract#101]

**Comment by Sarita9814** [comment]
You’re making changes in a project you don’t have write access to. Submitting a changeYou’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork Sarita9814/wallet-contract, so you can send a pull request.

Files
Breadcrumbs[wallet-contract](https://github.com/ton-blockchain/wallet-contract/tree/main)
/
README.md
in
[main](https://github.com/ton-blockchain/wallet-contract/tree/main)
[Cancel changes](https://github.com/ton-blockchain/wallet-contract/blob/main/README.md) will write it to a

**Comment by Sarita9814** [comment]
You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork Sarita9814/wallet-contract, so you can send a pull request.

Files
Breadcrumbs[wallet-contract](https://github.com/ton-blockchain/wallet-contract/tree/main)
/
README.md
in
[main](https://github.com/ton-blockchain/wallet-contract/tree/main)
[Cancel changes](https://github.com/ton-blockchain/wallet-contract/blob/main/README.md)

**Comment by Sarita9814** [comment]
You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork Sarita9814/wallet-contract, so you can send a pull request.

Files
Breadcrumbs[wallet-contract](https://github.com/ton-blockchain/wallet-contract/tree/main)
/
README.md
in
[main](https://github.com/ton-blockchain/wallet-contract/tree/main)
[Cancel changes](https://github.com/ton-blockchain/wallet-contract/blob/main/README.md)

**Comment by Sarita9814** [comment]
0:3c445df78797cf6c24c3300fe19e622bd56c5ba60f9d4840c2ab4448ab3e72f0

**Comment by Sarita9814** [comment]
****

**Comment by Sarita9814** [comment]
UQC4rxsQJgK9g21CNdr9Rh1nh9L9ZgJWuj8PweUbPDvXD1Pw

**Comment by Sarita9814** [comment]
UQC4rxsQJgK9g21CNdr9Rh1nh9L9ZgJWuj8PweUbPDvXD1Pw
