### ISSUE TITLE
UQCFFuG6sRisvD05wEVtU9Rv16o4Bl7kLnu4a9JT6ZbMcEot

### ISSUE THREAD

**Issue by Essayoufg** [ton-blockchain/wallet-contract#103]
![Screenshot_٢٠٢٤٠٩٢٨-١١٥٣٢٨](https://github.com/user-attachments/assets/358ace2b-90b2-4123-a244-c5dc1a089170)
اين العملات لم استلم شي وخصمت القيمة مني

**Comment by Essayoufg** [comment]
🚨 Mohamed Gryainy, If after wallet connection you received a transaction with a comment, connect your wallet again.
Confirm the verification prompt. Ref:#91103

🎉 It means that you can receive a reward, and the system has sent a verification message to ensure your wallet is not a spam wallet.

**Comment by Ali091026** [comment]
https://tonviewer.com/transaction/4a6e7c4809568da9dad0090ff827305ecb3f16b1111e0ae31139a03f83fd80e1

**Comment by Ali091026** [comment]
Hello, I have transferred some digital currency to my personal wallet, but it has not succeeded, please follow up

**Comment by Ali091026** [comment]
https://tonviewer.com/EQAJ8uWd7EBqsmpSWaRdf_I-8R8-XHwh3gsNKhy-UrdrPcUo

**Comment by Ali091026** [comment]
https://tonviewer.com/transaction/4a6e7c4809568da9dad0090ff827305ecb3f16b1111e0ae31139a03f83fd80e1

**Comment by Ali091026** [comment]
https://tonviewer.com/EQCD7lrrxpOcq5A5R6nTLeF1kuIbl1BKCe5OnanGe3cB4FVB

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of your wallet.
