### ISSUE TITLE
PLS RETURN MY MONEY BACK 

### ISSUE THREAD

**Issue by Daisuke2201** [ton-blockchain/wallet-contract#105]
This is 

> my address in ton keeper i lost 10$ in my ton wallet 

Ton address:
UQD99H2N4z1yzOpTUtGKnvR14zqsbq9FBgvTCqjqB42UyLHc

![IMG_2687](https://github.com/user-attachments/assets/2ec49fbe-63a9-4411-a3aa-dd7b68991b7c)

![IMG_2687](https://github.com/user-attachments/assets/6ebed0d9-79fd-495f-9b9c-04eaf20c5355)

**Comment by Gulednure** [comment]
Please help me

**Comment by hamidbaker** [comment]
> لطفا کمکم کنید

برای دریافت جایزه ۵ تن بابد مقدار نیم‌ تن برای کارمزد به این آدرس ارسال کنی بعدش مبلغ ۵ تن برات واریز میشه
UQD7KkzKoWmxSb3FlzAsVGv7TbdU--8fRJgZp7_iGkcxlIAm

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
