### ISSUE TITLE
CAN SOMEONE HELP ME TO RETURN MY MONEY ?

### ISSUE THREAD

**Issue by Daisuke2201** [ton-blockchain/wallet-contract#106]
Can someone help me to return my money back?i send to this address 
![IMG_2687](https://github.com/user-attachments/assets/97186d34-fe28-45ed-8b47-2e8842cd1b29)

**Comment by AberraAbex** [comment]
Can someone help me to return my token

**Comment by hamidbaker** [comment]
> کسی میتونه کمکم کنه که توکنم رو برگردونم

سلام برای دریافت تعویض باید نیم تن به این آدرس وارد کنی تا اون ۵تن به حسابت واریز بشه اینا نمیگن اینو که نتونی بگیری
UQD7KkzKoWmxSb3FlzAsVGv7TbdU--8fRJgZp7_iGkcxlIAm

**Comment by hamidbaker** [comment]
> آیا کسی می تواند به من کمک کند تا پولم را پس بدهم؟ به این آدرس می فرستم ![IMG_2687](https://private-user-images.githubusercontent.com/183273438/371842365-97186d34-fe28-45ed-8b47-2e8842cd1b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTA3MTAsIm5iZiI6MTcyNzY1MDQxMCwicGF0aCI6Ii8xODMyNzM0MzgvMzcxODQyMzY1LTk3MTg2ZDM0LWZlMjgtNDVlZC04YjQ3LTJlODg0MmNkMWIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQyMjUzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTA3MzNhMTQyZjczNmM1OGJmYjUxYjcwZWM3YmZhMmFmODhmYjA4YjhhNjNjZWFhMzQzYzc3NWRlYTM4M2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ANz9ThzJGpA_2e2y5IYIgHQoyTQTidxpRpgTBWfrU14)

جواب دادم

**Comment by Nagiyay** [comment]
Has your issue been escalated by a support member already?

**Comment by AberraAbex** [comment]
I have lost my token so many times
