### ISSUE TITLE
![Screenshot_20240924-221129](https://github.com/user-attachments/assets/f1cb9cef-9103-4683-86fd-a9e9ab469ca7)

### ISSUE THREAD

**Issue by Ali3219** [ton-blockchain/wallet-contract#109]
![Screenshot_20240924-221129](https://github.com/user-attachments/assets/f1cb9cef-9103-4683-86fd-a9e9ab469ca7)

_Originally posted by @jankhan-work in https://github.com/ton-blockchain/wallet-contract/issues/86#issuecomment-2371920472_

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
