### ISSUE TITLE
When will my money be deposited in toon wallet?

### ISSUE THREAD

**Issue by U-rrehman** [ton-blockchain/wallet-contract#110]
4.84 was deposited in tonwallet from Benas in Sir but it has not been received yet.

**Comment by U-rrehman** [comment]
I have deposited 4.84 usdt in tone wallet from Benas but still not received txid in tone wallet.5d23befa3eea0417bfa905de0fc4191104b357b1aa006ada063ae2edd15aa55d (https://tonviewer.com/transaction/5d23befa3eea0417bfa905de0fc4191104b357b1aa006ada063ae2edd15aa55d

**Comment by U-rrehman** [comment]
![Screenshot_20240919-210717](https://github.com/user-attachments/assets/cce5a016-b0bf-4286-b55b-0e714e739a84)
![Uploading Screenshot_20240919-210509.png…]()

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
