### ISSUE TITLE
Can someone help me to return my token

### ISSUE THREAD

**Issue by davoodda60** [ton-blockchain/wallet-contract#112]
![Screenshot_۲۰۲۴۱۰۰۱_۰۲۴۳۳۷_Tonkeeper](https://user-images.githubusercontent.com/29032453/372304773-e2a1f150-3441-4189-9bb8-f2bb80302700.jpg)
              Can someone help me to return my token

_Originally posted by @AberraAbex in https://github.com/ton-blockchain/wallet-contract/issues/106#issuecomment-2381418021_

**Comment by Nagiyay** [comment]
Has your issue been escalated by a support member already?

**Comment by Sammxes** [comment]
I think that all this that telegram is doing is a scam because I have heard and I have been robbed of the official channels and mini applications.😒 keep your money safe

**Comment by 8222md** [comment]
Je veux récupérer mes jetons

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by Ki-tich** [comment]
My toke
