### ISSUE TITLE
Wallet hacking

### ISSUE THREAD

**Issue by MA24974** [ton-blockchain/wallet-contract#12]
The entire balance of Tone Keeper wallet has been sent to this address by a bot related to TapSwap and it is a scam.
UQBZIuyEbu-y5dICWvN2RXyXsdsheYtgccnLWhsLh0D5FK74[
![Screenshot_20240610_140328_Tonkeeper](https://github.com/ton-blockchain/wallet-contract/assets/172264318/be84ea5f-8999-4225-be85-50387e47c479)
![Screenshot_20240610_140310_Tonkeeper](https://github.com/ton-blockchain/wallet-contract/assets/172264318/15221c41-1b07-4c2e-83cf-423dd79335da)
](url)

**Comment by Good1-svg** [comment]
Where is the wallet passkey

**Comment by Cashap162** [comment]
How can I start hacking wallet

**Comment by Cashap162** [comment]
> Where is the wallet passkey
>

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_[](url)

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_[](url)

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_[](url)

> The entire balance of Tone Keeper wallet has been sent to this address by a bot related to TapSwap and it is a scam. UQBZIuyEbu-y5dICWvN2RXyXsdsheYtgccnLWhsLh0D5FK74[ ![Screenshot_20240610_140328_Tonkeeper](https://private-user-images.githubusercontent.com/172264318/338154544-be84ea5f-8999-4225-be85-50387e47c479.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzYyNjIsIm5iZiI6MTcyNDgzNTk2MiwicGF0aCI6Ii8xNzIyNjQzMTgvMzM4MTU0NTQ0LWJlODRlYTVmLTg5OTktNDIyNS1iZTg1LTUwMzg3ZTQ3YzQ3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwOTA2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWNlNTU0OTY5Y2Y4ZjAwOWQxMDFhMTBiNWQxNTAwMmVlNTM2OGRlOTk3YTExY2E3OWE2ZjFkNWY5YWY5NTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2hcgO3B1idaUpzupUsqBleahZifoLI72CONn3oBAxbc) ![Screenshot_20240610_140310_Tonkeeper](https://private-user-images.githubusercontent.com/172264318/338154570-15221c41-1b07-4c2e-83cf-423dd79335da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzYyNjIsIm5iZiI6MTcyNDgzNTk2MiwicGF0aCI6Ii8xNzIyNjQzMTgvMzM4MTU0NTcwLTE1MjIxYzQxLTFiMDctNGMyZS04M2NmLTQyM2RkNzkzMzVkYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwOTA2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmQ2M2EwOWYxMDQxZjM4Njg5MDY4MWEyOWVhYWE3MjhiMDMwODM4Yjk4NGE1YWUzMTM4NTllZjJhZWQwZWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cK9-iCVm_WNeE1nyL-l7e2dD6-mD0sZf3WHq9oOqufo) ](url)

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_[](url)

> The entire balance of Tone Keeper wallet has been sent to this address by a bot related to TapSwap and it is a scam. UQBZIuyEbu-y5dICWvN2RXyXsdsheYtgccnLWhsLh0D5FK74[ ![Screenshot_20240610_140328_Tonkeeper](https://private-user-images.githubusercontent.com/172264318/338154544-be84ea5f-8999-4225-be85-50387e47c479.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzYyNjIsIm5iZiI6MTcyNDgzNTk2MiwicGF0aCI6Ii8xNzIyNjQzMTgvMzM4MTU0NTQ0LWJlODRlYTVmLTg5OTktNDIyNS1iZTg1LTUwMzg3ZTQ3YzQ3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwOTA2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWNlNTU0OTY5Y2Y4ZjAwOWQxMDFhMTBiNWQxNTAwMmVlNTM2OGRlOTk3YTExY2E3OWE2ZjFkNWY5YWY5NTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2hcgO3B1idaUpzupUsqBleahZifoLI72CONn3oBAxbc) ![Screenshot_20240610_140310_Tonkeeper](https://private-user-images.githubusercontent.com/172264318/338154570-15221c41-1b07-4c2e-83cf-423dd79335da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzYyNjIsIm5iZiI6MTcyNDgzNTk2MiwicGF0aCI6Ii8xNzIyNjQzMTgvMzM4MTU0NTcwLTE1MjIxYzQxLTFiMDctNGMyZS04M2NmLTQyM2RkNzkzMzVkYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwOTA2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmQ2M2EwOWYxMDQxZjM4Njg5MDY4MWEyOWVhYWE3MjhiMDMwODM4Yjk4NGE1YWUzMTM4NTllZjJhZWQwZWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cK9-iCVm_WNeE1nyL-l7e2dD6-mD0sZf3WHq9oOqufo) ](url)

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_[](url)

**Comment by Mohammadhoseynkhaleqi** [comment]
UQD5NG3O8GBqxXOJTCZnnPCw89u---5-_QrIEaADqT_X4Wj_[](url)

> The entire balance of Tone Keeper wallet has been sent to this address by a bot related to TapSwap and it is a scam. UQBZIuyEbu-y5dICWvN2RXyXsdsheYtgccnLWhsLh0D5FK74[ ![Screenshot_20240610_140328_Tonkeeper](https://private-user-images.githubusercontent.com/172264318/338154544-be84ea5f-8999-4225-be85-50387e47c479.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzYyNjIsIm5iZiI6MTcyNDgzNTk2MiwicGF0aCI6Ii8xNzIyNjQzMTgvMzM4MTU0NTQ0LWJlODRlYTVmLTg5OTktNDIyNS1iZTg1LTUwMzg3ZTQ3YzQ3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwOTA2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWNlNTU0OTY5Y2Y4ZjAwOWQxMDFhMTBiNWQxNTAwMmVlNTM2OGRlOTk3YTExY2E3OWE2ZjFkNWY5YWY5NTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2hcgO3B1idaUpzupUsqBleahZifoLI72CONn3oBAxbc) ![Screenshot_20240610_140310_Tonkeeper](https://private-user-images.githubusercontent.com/172264318/338154570-15221c41-1b07-4c2e-83cf-423dd79335da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzYyNjIsIm5iZiI6MTcyNDgzNTk2MiwicGF0aCI6Ii8xNzIyNjQzMTgvMzM4MTU0NTcwLTE1MjIxYzQxLTFiMDctNGMyZS04M2NmLTQyM2RkNzkzMzVkYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwOTA2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmQ2M2EwOWYxMDQxZjM4Njg5MDY4MWEyOWVhYWE3MjhiMDMwODM4Yjk4NGE1YWUzMTM4NTllZjJhZWQwZWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cK9-iCVm_WNeE1nyL-l7e2dD6-mD0sZf3WHq9oOqufo) ](url)
