### ISSUE TITLE
Func compilation error: ( function `config_param` undefined )

### ISSUE THREAD

**Issue by NaNOteh** [ton-blockchain/wallet-contract#121]
Func compilation error: ( function `config_param` undefined )
                                                             cannot generate code for function `config_param`:
           func/simple-subscription-plugin.fc:16:20: error: config_param
                                                                            int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64);  11:47:55 
Func compilation error: ( function `config_param` undefined )
                                                             cannot generate code for function `config_param`:
           func/simple-subscription-plugin.fc:16:20: error: config_param
                                                                            int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64);  11:47:55 
Func compilation error: func/wallet-v4-code.fc:1:1: error: FunC version 0.4.1 does not satisfy condition =0.2.0
              #pragma version =0.2.0;  11:55:44 

_Originally posted by @Kyrylog in https://github.com/ton-blockchain/wallet-contract/issues/9

**Comment by Antorhalder** [comment]
> Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: func/wallet-v4-code.fc:1:1: error: FunC version 0.4.1 does not satisfy condition =0.2.0 #pragma version =0.2.0; 11:55:44
> 
> _Originally posted by @Kyrylog in #9_

**Comment by hossen71** [comment]
> > Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: func/wallet-v4-code.fc:1:1: error: FunC version 0.4.1 does not satisfy condition =0.2.0 #pragma version =0.2.0; 11:55:44
> 
>
