### ISSUE TITLE
> HAMSTER TOKEN NOT APPEARING IN MY TONKEEPER.

### ISSUE THREAD

**Issue by Semmymy** [ton-blockchain/wallet-contract#125]
> HAMSTER TOKEN NOT APPEARING IN MY TONKEEPER.
> My Hamster token is not showing in my tonkeeper. In the Blockchain, the token can't be transferred or used for transaction. 
> Please I need the token to appear in my ton wallet, not in Blockchain. It's been almost useless since it's given after Hamster Airdrop in September 26.

semmymyy@gmail.com

_Originally posted by @Semmymy in https://github.com/ton-blockchain/wallet-contract-v5/issues/75#issuecomment-2395710635_

**Comment by Rezacb0413** [comment]
> > HAMSTER TOKEN NOT APPEARING IN MY TONKEEPER.
> > My Hamster token is not showing in my tonkeeper. In the Blockchain, the token can't be transferred or used for transaction. 
> > Please I need the token to appear in my ton wallet, not in Blockchain. It's been almost useless since it's given after Hamster Airdrop in September 26.
> 
> semmymyy@gmail.com
> 
> _Originally posted by @Semmymy in https://github.com/ton-blockchain/wallet-contract-v5/issues/75#issuecomment-2395710635_

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
