### ISSUE TITLE
> Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: func/wallet-v4-code.fc:1:1: error: FunC version 0.4.1 does not satisfy condition =0.2.0 #pragma version =0.2.0; 11:55:44

### ISSUE THREAD

**Issue by Evilwa1** [ton-blockchain/wallet-contract#156]
> Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: func/wallet-v4-code.fc:1:1: error: FunC version 0.4.1 does not satisfy condition =0.2.0 #pragma version =0.2.0; 11:55:44

_Originally posted by @Djahadu34 in https://github.com/ton-blockchain/wallet-contract/issues/9#issuecomment-2425225401_

**Comment by Evilwa1** [comment]
UQD72Yp47y8338TpQgnUrJy53XH_qsZsybpscA01HJAN_sDQ

**Comment by Kurdlove** [comment]
> Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: ( function `config_param` undefined ) cannot generate code for function `config_param`: func/simple-subscription-plugin.fc:16:20: error: config_param int lump_price = config_param(config_index).begin_parse().skip_bits(8).preload_uint(64); 11:47:55 Func compilation error: func/wallet-v4-code.fc:1:1: error: FunC version 0.4.1 does not satisfy condition =0.2.0 #pragma version =0.2.0; 11:55:44

**Comment by Kurdlove** [comment]
``` agma version =0.2.0; 11:55:44

**Comment by Mina2889** [comment]
https://github.com/ton-blockchain/wallet-contract/issues/183#issuecomment-2465872570

در تاریخ جمعه ۸ نوامبر ۲۰۲۴،‏ ۹:۱۳ ب.ظ Kurdlove ***@***.***>
نوشت:
