### ISSUE TITLE
> > text: Receive 0.14 TON + 100 USDT

### ISSUE THREAD

**Issue by Hamed1370m** [ton-blockchain/wallet-contract#183]
> > text: Receive 0.14 TON + 100 USDT

_Originally posted by @LuCaSiNo40 in https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911_

**Comment by Hamed1370m** [comment]
UQCIZh-syryRUHb2GfgpEFA9aRvj3KWyWgg81noOjyY
cb_n3

Im wallet tonkepper

**Comment by Hamed1370m** [comment]
> > text: Receive 0.14 TON + 100 USDT

**Comment by Hamed1370m** [comment]
[https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451290138](url)

**Comment by Mina2889** [comment]
maingit-branch--m-main-<BRANCH>-git-fetch-origin-git-branch--u-origin/<BRANCH>-<BRANCH>-git-remote-set-head-origin--a

در تاریخ جمعه ۸ نوامبر ۲۰۲۴،‏ ۱۱:۴۸ ب.ظ Hamed1370m ***@***.***>
نوشت:

**Comment by Mina2889** [comment]
> ```
>       > > text: Receive 0.14 TON + 100 USDT
> ```

**Comment by Mina2889** [comment]
Duplicate of #

**Comment by Mina2889** [comment]
> > text: Receive 0.14 TON + 100 USDT

**Comment by Mina2889** [comment]
https://github.com/ton-blockchain/wallet-contract/issues/183#issuecomment-2465872570

**Comment by Kawser13011991** [comment]
> ```
>           > > text: Receive 0.14 TON + 100 USDT
> ```
> 
> _Originally posted by @LuCaSiNo40 in [ton-blockchain/TEPs#119 (comment)](https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911)_

#183

**Comment by pamparon** [comment]
Yes

**Comment by Przem-SS** [comment]
> ```
>           > > text: Receive 0.14 TON + 100 USDT
> ```
> 
> _Originally posted by @LuCaSiNo40 in [ton-blockchain/TEPs#119 (comment)](https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911)_

          > > text: Receive 0.14 TON + 100 USDT

**Comment by Przem-SS** [comment]
Receive 0.14 TON + 100 USDT #183

**Comment by pamparon** [comment]
What?
