### ISSUE TITLE
Confirmación 

### ISSUE THREAD

**Issue by ZACKTB8** [ton-blockchain/wallet-contract#21]
https://github.com/ton-blockchain/mytonctrl/commit/27bbb64bf76ecbc0be8a28132c28ebdecb6a90cf

**Comment by lokmanmorady267** [comment]
0x738cd4c13e7c158c56af6357eb0d18792e7bf618

**Comment by lokmanmorady267** [comment]
0x738cd4c13e7c158c56af6357eb0d18792e7bf618
