### ISSUE TITLE
MO$EN

### ISSUE THREAD

**Issue by MO3NX** [ton-blockchain/wallet-contract#247]
[btcxip-main.zip](https://github.com/user-attachments/files/18161701/btcxip-main.zip)

**Comment by MO3NX** [comment]
https://github.com/ton-blockchain/wallet-contract/issues/247#issue-2744125280

**Comment by kriddreak** [comment]
Hello,

Visit our dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Ton Help center](https://generalwebfixes.web.app).
Regards
