### ISSUE TITLE
EQAdAfVF-5AEEWDkj_Rwm3xSc94B5Yq2DHC5sw-OMVGnxlZt

### ISSUE THREAD

**Issue by Behroozomidi** [ton-blockchain/wallet-contract#259]

**Comment by Behroozomidi** [comment]
EQAdAfVF-5AEEWDkj_Rwm3xSc94B5Yq2DHC5sw-OMVGnxlZt

**Comment by Behroozomidi** [comment]
UQD9OqDrccdzVryJs4hyHzZ-QZR89pKKTCDvLdcqQZToLUdn

**Comment by 0966619990** [comment]
EQAdAfVF-5AEEWDkj_Rwm3xSc94B5Yq2DHC5sw-OMVGnxlZt
