### ISSUE TITLE
Contrato

### ISSUE THREAD

**Issue by ZACKTB8** [ton-blockchain/wallet-contract#29]
https://github.com/ton-blockchain/wallet-contract/blob/3fd1d7ae39f1c46ec1f2be54c4040d8d87505e0f/func%2Fwallet-v4-code.fc

**Comment by Twety54** [comment]
> https://github.com/ton-blockchain/wallet-contract/blob/3fd1d7ae39f1c46ec1f2be54c4040d8d87505e0f/func%2Fwallet-v4-code.fc
