### ISSUE TITLE
A

### ISSUE THREAD

**Issue by aboneha** [ton-blockchain/wallet-contract#45]
My transaction not confirmed

**Comment by Michellecasiddy** [comment]
Hey there @aboneha!

Thank you for reaching out!

Could you provide more details about the issue you're experiencing, such as screenshots or your wallet address/transaction ID? If you'd rather not share these here, you can also contact the live support team directly via [Ton-Blockchain DApps Support Ticket Requests](https://github.com/ton-blockchain/wallet-contract/issues/thedappsupport.com) using ticket ID TON7464.

Just click the live chat icon at the bottom corner of the page to start a chat with a support agent.

Regards.

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
