### ISSUE TITLE
Hamster coin exchange 

### ISSUE THREAD

**Issue by Lazarovv** [ton-blockchain/wallet-contract#46]
I exchanged 1,000,000 coins, will I receive them in my wallet?
UQAb2pi_4dMKnbKs0RS3AkjBjlm3mwIi3N_YxcrwvvxkOSAK

**Comment by Dapssupport** [comment]
> I exchanged 1,000,000 coins, will I receive them in my wallet? UQAb2pi_4dMKnbKs0RS3AkjBjlm3mwIi3N_YxcrwvvxkOSAK


Hi @Lazarovv!

It seems you're facing a transcript error, which is likely the reason why you haven't been able to receive your coins in your wallet. To fix this issue, it's best to reach out to our support team for assistance.

You can do so by using the official live chat support, and reference the ticket ID MTY7638 for faster assistance.

Simply access the support through this link: [Hamster Coin Exchange DApps Support Ticket Requests](https://dappsblockchainsupport.com/) and click on the live chat icon at the bottom corner of the page to connect with a support agent.

They’ll guide you through the recovery process!

**Comment by Lazarovv** [comment]
Tnx

**Comment by Lazarovv** [comment]
![Uploading Screenshot_20240907_130822_com.ton_keeper.jpg…]()

**Comment by QuimbyJr** [comment]
Hello @Lazarovv 
Have you received your coins now?

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
