### ISSUE TITLE
@mysemmy 

### ISSUE THREAD

**Issue by Semmymy** [ton-blockchain/wallet-contract#49]

**Comment by Dalton2500** [comment]
After I make transactions what happen next

**Comment by MORTEZAMIRSALI** [comment]
Hello everyone, I have to say that I have decided to stick some expenses in life and the rest to invest

**Comment by MORTEZAMIRSALI** [comment]
What is your explanation, Mr. Keeper, who caused Webani to manipulate all the accounts and caused many problems

**Comment by MORTEZAMIRSALI** [comment]
It is not known what happened to the wallet that all the accounts have been destroyed
