### ISSUE TITLE
UQDgFwiokL1ojVwXa3Ac7xCLfGB0Ti0foSw5NZ48Aj_vhs_6

### ISSUE THREAD

**Issue by Ymamhmaidey** [ton-blockchain/wallet-contract#51]
b5ee9c720102040100012400029ec698c9c016badb5b6b09a336cae1ade5249b36ff29f2f25c26c97d163d4f66fa04448db69c769c15fcdd06c3024148b31cc842b065d82351fa0f64e5b1812f0329a9a31766e0fecf00000012000303010201cb62000a82a9c2ae8c870778f716c7a594ea3430c07aa136a7df5bf1ab429b029b809a2023c3460000000000000000000000000000abcdef13000000000000000041c03a180801c02e1151217ad11ab82ed6e039de2116f8c0e89c5a3f4258726b3c78047fdf0d0300c04200700b8454485eb446ae0bb5b80e778845be303a27168fd0961c9acf1e011ff7c3253e4bee000000000000000000000000000000000000f09f94925265636569766520746f2067657420352e3633207473544f4e202b203437322055534454000800000000

**Comment by Divangbuon** [comment]
Hi

**Comment by Divangbuon** [comment]
Kim bnj hjjji
