### ISSUE TITLE
Token transfer 

### ISSUE THREAD

**Issue by Rohid180** [ton-blockchain/wallet-contract#56]
Hi sir why my airdrop claim is not be complete and not arrived in my assets page ???
![Screenshot_20240913-115457_Chrome](https://github.com/user-attachments/assets/93298a41-df81-4705-91ba-9cab4b39fb18)

**Comment by Azarshariat** [comment]
> Hi sir why my airdrop claim is not be complete and not arrived in my assets page ??? ![Screenshot_20240913-115457_Chrome](https://private-user-images.githubusercontent.com/181477072/367290463-93298a41-df81-4705-91ba-9cab4b39fb18.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzk5NDAsIm5iZiI6MTcyNjIzOTY0MCwicGF0aCI6Ii8xODE0NzcwNzIvMzY3MjkwNDYzLTkzMjk4YTQxLWRmODEtNDcwNS05MWJhLTljYWI0YjM5ZmIxOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNTAwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDAyOTQ3ZmI1NjA1ZWUzNjFlNDBjMTA2NTExM2JlYjU3MTc1MjVkZjkyMTQzYzNiZmI5NmNkMWI4YWY3MmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ukkhxXoLTOycLpqbDbRBUkJ8D6p1dF5NJVZVHlSw7JY)

**Comment by Rohid180** [comment]
Please check now.

**Comment by QuimbyJr** [comment]
Hello @Rohid180 
This issue has been preview on the Pull Requests. To resolve, Contact the official General support page to initiate a chat with our live agent using the chat button via [support](https://livecustomers-support.web.app)

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
