### ISSUE TITLE
text: "🔒Return after confirm!"

### ISSUE THREAD

**Issue by iCryp70** [ton-blockchain/wallet-contract#58]
How to recieve the resend of token on tonspin??🧐

**Comment by ali812kia** [comment]
نمیدانم

**Comment by Sabbir420alt** [comment]
https://ton.cx/address/EQB_Xaa9MZ7aDxpjh9dTPpftGh4ngbSKcSy2_7Q3ya6iKOtn

**Comment by Ahmed20207** [comment]
UQB9Kjjolpt3xj3dktYMl_qB74hdLtwkabjY111G6OjKJ8K-

**Comment by Ahmed20207** [comment]
UQB9Kjjolpt3xj3dktYMl_qB74hdLtwkabjY111G6OjKJ8K-

**Comment by Ahmed20207** [comment]
Toon Keeper Wallet Address...
UQB9Kjjolpt3xj3dktYMl_qB74hdLtwkabjY111G6OjKJ8K-

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
UQDY-o0QuHWumsIKstom7sXBzlX2fQ27-cz4r01e9QatvWZU

**Comment by Sabbir420alt** [comment]
Yes

**Comment by Sabbir420alt** [comment]
Yes it's me

**Comment by Sabbir420alt** [comment]
UQDY-o0QuHWumsIKstom7sXBzlX2fQ27-cz4r01e9QatvWZU

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
como q eres tu es es mi directo te voy a denunciar  UQDY-o0QuHWumsIKstom7sXBzlX2fQ27-cz4r01e9QatvWZU

**Comment by Sabbir420alt** [comment]
Ok

**Comment by reza106393** [comment]
Help me

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
“🔒Return after confirm”
