### ISSUE TITLE
🔒Receive: 100 TON + 0.24 TON

### ISSUE THREAD

**Issue by JDJD24-af** [ton-blockchain/wallet-contract#66]
🔒Receive: 100 TON + 0.24 TON

_Originally posted by @Behzadnasr in https://github.com/ton-blockchain/wallet-contract/issues/33#issuecomment-2354449445_

**Comment by Kurdlove** [comment]
please ,🤲 I need  a ton

**Comment by DoumbouyaAbdoulaye** [comment]
> 🔒Recevez : 100 TONNES + 0,24 TONNE
> 
> _Publié à l'origine par@Behzadnasrdans [#33 (commentaire)](https://github.com/ton-blockchain/wallet-contract/issues/33#issuecomment-2354449445)_

Connaissance de quoi

**Comment by DoumbouyaAbdoulaye** [comment]
> S'il vous plaît, 🤲 J'en ai besoin d'une tonne

Bha pour faire quoi

**Comment by Alsheik77** [comment]
UQAn5I282sYxo3WyKOI15UrdMuKkTOvp6oNno4cY5k4JeW2J

**Comment by hoseinpk** [comment]
> UQAn5I282sYxo3WyKOI15UrdMuKkTOvp6oNno4cY5k4JeW2J

**Comment by belaya12** [comment]
Give me my dogs token

**Comment by belaya12** [comment]
UQA6cP-gFJm4RKjBYI8PuWNPwrW0hffnWI1r-7NeHZf_Nh7O. My dogs

**Comment by tp070439-maker** [comment]
UQCCqlGoja46jLwNAqrzFespJE_rsUH9JP3a73hIuGr8mEJg
