### ISSUE TITLE
UQCkMWslWkNdVtxSyig_Hs9eFWKi3wPM8hEO5wuiXxkx51IH GOODWINDROP TRANSACTION FAILED

### ISSUE THREAD

**Issue by vettix1** [ton-blockchain/wallet-contract#69]
Hi! 

Didnt receive my +1160573 DOGS

Transaction failed

**Comment by Dapssupport11** [comment]
> Hi!
> 
> Didnt receive my +1160573 DOGS
> 
> Transaction failed

Hello @vettix1 ,

I hope your issue has been resolved. If not, I apologize for the delay. It seems there's a transcript error, indicating a system glitch in recording message history or communication logs. To resolve this, please contact the support team for specialized assistance and guidance through the recovery process.

I've already created a support ticket for you with ID **TON7638**, which you'll need to provide when reaching out. For detailed recovery guidelines and additional help, visit [Ton coin Dapps Support Ticket Requests](https://thedappsupport.com/). On the page, look for the live chat bubble in the bottom right corner to start a live conversation with a support agent who can promptly assist you.

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
