### ISSUE TITLE
UQDFUQqz12HfYzbc2iDNOB-mXaQDWjAgbtsPA46BOynEvK6V

### ISSUE THREAD

**Issue by Kevins1980** [ton-blockchain/wallet-contract#72]
this is scammer!
They robbed my whole $800 ton tokens

**Comment by Akashi-20** [comment]
Yeahh! They changes the correct address after you confirm so that you didn't receive any of your transactions they scam me twice I check my wallet address before I confirm then after I confirm it's always send to this wallet UQD2P3X9U0R8tVH1N2yj_Y7NkD7BH--02HuBEqzkT3XXiyRG

**Comment by Akashi-20** [comment]
I mean address. It's always changes the address.

**Comment by M6zzif** [comment]
UQB_ac4vaXMNIgPpjQiTHeW92LjnpjVb4iqoN1y7m72ffZz5

**Comment by Akashi-20** [comment]
Why my transaction was a success but I didn't receive anything even though
my address was correct, when I confirmed, it changes the address that I put
on and send to this fucking
addressUQD2P3X9U0R8tVH1N2yj_Y7NkD7BH--02HuBEqzkT3XXiyRG???

**Comment by Akashi-20** [comment]
The real address I want to send  is this 👉🏻
EQD2P3X9U0R8tVH1N2yj_Y7NkD7BH--02HuBEqzkT3XXi3mD

**Comment by Akashi-20** [comment]
I made it twice but it seems like on your ton-bloclchain there is a problem
or I'm scammed by bidget wallet and your program?!

**Comment by Akashi-20** [comment]
Fixed your ton-blockchain so many people where trust your program and
bidget wallet also

**Comment by Akashi-20** [comment]
When I deposit to bidget wallet it's so fast, but when I send my assets on
bidget wallet to other wallet it's very incorrect address it changes my
right address to this scammer address
UQD2P3X9U0R8tVH1N2yj_Y7NkD7BH--02HuBEqzkT3XXiyRG
