### ISSUE TITLE
Hello, don't be bored, everyone, Tonkeeper, you don't intend to cooperate, because I haven't been there for several years because of problems, instead of thanking my financial resources for helping to climb the tanks, all of them have created obstacles.  Be trustworthy people, he is trying to create an obstacle to own my belongings. Friends, I have been here for some time. Tunkeeper has not only spared 1 cent from my wealth, but he has reduced all the transactions from me on AirDrabs, but all of them are a violation of this example of violation and anti-citizen rights and abuse.  Absolutely from a citizen, if these were realistic and justice-oriented, even if my children came to control my assets for 60 years, there would not have been so much mistreatment and tension between all subscribers.  Don't stop trusting and be convinced of your right

### ISSUE THREAD

**Issue by Jamilkhalilzad** [ton-blockchain/wallet-contract#88]
Hello, don't be bored, everyone, Tonkeeper, you don't intend to cooperate, because I haven't been there for several years because of problems, instead of thanking my financial resources for helping to climb the tanks, all of them have created obstacles.  Be trustworthy people, he is trying to create an obstacle to own my belongings. Friends, I have been here for some time. Tunkeeper has not only spared 1 cent from my wealth, but he has reduced all the transactions from me on AirDrabs, but all of them are a violation of this example of violation and anti-citizen rights and abuse.  Absolutely from a citizen, if these were realistic and justice-oriented, even if my children came to control my assets for 60 years, there would not have been so much mistreatment and tension between all subscribers.  Don't stop trusting and be convinced of your right

_Originally posted by @MORTEZAMIRSALI in https://github.com/ton-blockchain/wallet-contract/issues/77#issuecomment-2364141975_

**Comment by aminoghabi1** [comment]
So very good

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of your wallet.
