### ISSUE TITLE
After I make transactions what happen next

### ISSUE THREAD

**Issue by Semmymy** [ton-blockchain/wallet-contract#91]
After I make transactions what happen next

_Originally posted by @Dalton2500 in https://github.com/ton-blockchain/wallet-contract/issues/49#issuecomment-2345055775_

**Comment by Semmymy** [comment]
> After I make transactions what happen next
> 
> _Originally posted by @Dalton2500 in https://github.com/ton-blockchain/wallet-contract/issues/49#issuecomment-2345055775_

**Comment by MORTEZAMIRSALI** [comment]
Hello, what happened to my tank and wallet, what did you do 😕😕
